# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

import numpy as np
from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _iric
else:
    import _iric

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)

def _checkErrorCode(ier):
    if ier == 0: return

    raise Exception('Error code ier={0}'.format(ier))

CG_MODE_READ = 0
CG_MODE_WRITE = 1
CG_MODE_MODIFY = 2

IRIC_MODE_READ = 0
IRIC_MODE_WRITE = 1
IRIC_MODE_MODIFY = 2

IRIC_OPTION_CANCEL = 1
IRIC_OPTION_DIVIDESOLUTIONS = 2
IRIC_OPTION_STDSOLUTION = 3

class IntArrayContainer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, size):
        _iric.IntArrayContainer_swiginit(self, _iric.new_IntArrayContainer(size))
    __swig_destroy__ = _iric.delete_IntArrayContainer

    def size(self):
        return _iric.IntArrayContainer_size(self)

    def value(self, index):
        return _iric.IntArrayContainer_value(self, index)

    def setValue(self, index, v):
        return _iric.IntArrayContainer_setValue(self, index, v)

    def pointer(self):
        return _iric.IntArrayContainer_pointer(self)

    def get(self):
        ret = np.zeros(self.size(), dtype=np.int32)
        for i in range(self.size()):
            ret[i] = self.value(i)
        return ret

    def set(self, vals):
        for i in range(self.size()):
            self.setValue(i, int(vals[i]))

# Register IntArrayContainer in _iric:
_iric.IntArrayContainer_swigregister(IntArrayContainer)

class RealArrayContainer(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def __init__(self, size):
        _iric.RealArrayContainer_swiginit(self, _iric.new_RealArrayContainer(size))
    __swig_destroy__ = _iric.delete_RealArrayContainer

    def size(self):
        return _iric.RealArrayContainer_size(self)

    def value(self, index):
        return _iric.RealArrayContainer_value(self, index)

    def setValue(self, index, v):
        return _iric.RealArrayContainer_setValue(self, index, v)

    def pointer(self):
        return _iric.RealArrayContainer_pointer(self)

    def get(self):
        ret = np.zeros(self.size(), dtype=np.float64)
        for i in range(self.size()):
            ret[i] = self.value(i)
        return ret

    def set(self, vals):
        for i in range(self.size()):
            self.setValue(i, float(vals[i]))

# Register RealArrayContainer in _iric:
_iric.RealArrayContainer_swigregister(RealArrayContainer)

# from iriclib_bc.h
def cg_iRIC_Read_BC_Count_WithGridId(fid, gid, type):
	num = _iric.cg_iRIC_Read_BC_Count_WithGridId(fid, gid, type)
	return num

def cg_iRIC_Read_BC_IndicesSize_WithGridId(fid, gid, type, num):
	ier, size = _iric.cg_iRIC_Read_BC_IndicesSize_WithGridId(fid, gid, type, num)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_BC_IndicesSize2_WithGridId(fid, gid, type, num):
	ier, size = _iric.cg_iRIC_Read_BC_IndicesSize2_WithGridId(fid, gid, type, num)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_BC_Integer_WithGridId(fid, gid, type, num, name):
	ier, value = _iric.cg_iRIC_Read_BC_Integer_WithGridId(fid, gid, type, num, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_BC_Real_WithGridId(fid, gid, type, num, name):
	ier, value = _iric.cg_iRIC_Read_BC_Real_WithGridId(fid, gid, type, num, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_BC_String_WithGridId(fid, gid, type, num, name):
	ier, strvalue = _iric.cg_iRIC_Read_BC_String_WithGridId(fid, gid, type, num, name)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Read_BC_FunctionalSize_WithGridId(fid, gid, type, num, name):
	ier, size = _iric.cg_iRIC_Read_BC_FunctionalSize_WithGridId(fid, gid, type, num, name)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_BC_FunctionalWithName_String_WithGridId(fid, gid, type, num, name, paramname):
	ier, strvalue = _iric.cg_iRIC_Read_BC_FunctionalWithName_String_WithGridId(fid, gid, type, num, name, paramname)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Clear_BC_WithGridId(fid, gid):
	ier = _iric.cg_iRIC_Clear_BC_WithGridId(fid, gid)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_Integer_WithGridId(fid, gid, type, num, name, value):
	ier = _iric.cg_iRIC_Write_BC_Integer_WithGridId(fid, gid, type, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_Real_WithGridId(fid, gid, type, num, name, value):
	ier = _iric.cg_iRIC_Write_BC_Real_WithGridId(fid, gid, type, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_String_WithGridId(fid, gid, type, num, name, value):
	ier = _iric.cg_iRIC_Write_BC_String_WithGridId(fid, gid, type, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_FunctionalWithName_String_WithGridId(fid, gid, type, num, name, paramname, value):
	ier = _iric.cg_iRIC_Write_BC_FunctionalWithName_String_WithGridId(fid, gid, type, num, name, paramname, value)
	_checkErrorCode(ier)


# from iriclib_cc.h
def cg_iRIC_Read_Integer(fid, name):
	ier, value = _iric.cg_iRIC_Read_Integer(fid, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_Real(fid, name):
	ier, value = _iric.cg_iRIC_Read_Real(fid, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_String(fid, name):
	ier, strvalue = _iric.cg_iRIC_Read_String(fid, name)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Read_FunctionalSize(fid, name):
	ier, size = _iric.cg_iRIC_Read_FunctionalSize(fid, name)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_FunctionalWithName_String(fid, name, paramname):
	ier, strvalue = _iric.cg_iRIC_Read_FunctionalWithName_String(fid, name, paramname)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Write_Integer(fid, name, value):
	ier = _iric.cg_iRIC_Write_Integer(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Real(fid, name, value):
	ier = _iric.cg_iRIC_Write_Real(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_String(fid, name, value):
	ier = _iric.cg_iRIC_Write_String(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_FunctionalWithName_String(fid, name, paramname, value):
	ier = _iric.cg_iRIC_Write_FunctionalWithName_String(fid, name, paramname, value)
	_checkErrorCode(ier)


# from iriclib_complex.h
def cg_iRIC_Read_Complex_Count_WithBaseId(fid, bid, groupname):
	ier, num = _iric.cg_iRIC_Read_Complex_Count_WithBaseId(fid, bid, groupname)
	_checkErrorCode(ier)
	return num

def cg_iRIC_Read_Complex_Integer_WithBaseId(fid, bid, groupname, num, name):
	ier, value = _iric.cg_iRIC_Read_Complex_Integer_WithBaseId(fid, bid, groupname, num, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_Complex_Real_WithBaseId(fid, bid, groupname, num, name):
	ier, value = _iric.cg_iRIC_Read_Complex_Real_WithBaseId(fid, bid, groupname, num, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_Complex_String_WithBaseId(fid, bid, groupname, num, name):
	ier, strvalue = _iric.cg_iRIC_Read_Complex_String_WithBaseId(fid, bid, groupname, num, name)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Read_Complex_FunctionalSize_WithBaseId(fid, bid, groupname, num, name):
	ier, size = _iric.cg_iRIC_Read_Complex_FunctionalSize_WithBaseId(fid, bid, groupname, num, name)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_Complex_FunctionalWithName_String_WithBaseId(fid, bid, groupname, num, name, paramname):
	ier, strvalue = _iric.cg_iRIC_Read_Complex_FunctionalWithName_String_WithBaseId(fid, bid, groupname, num, name, paramname)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Clear_Complex_WithBaseId(fid, bid):
	ier = _iric.cg_iRIC_Clear_Complex_WithBaseId(fid, bid)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_Integer_WithBaseId(fid, bid, groupname, num, name, value):
	ier = _iric.cg_iRIC_Write_Complex_Integer_WithBaseId(fid, bid, groupname, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_Real_WithBaseId(fid, bid, groupname, num, name, value):
	ier = _iric.cg_iRIC_Write_Complex_Real_WithBaseId(fid, bid, groupname, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_String_WithBaseId(fid, bid, groupname, num, name, value):
	ier = _iric.cg_iRIC_Write_Complex_String_WithBaseId(fid, bid, groupname, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_FunctionalWithName_String_WithBaseId(fid, bid, groupname, num, name, paramname, value):
	ier = _iric.cg_iRIC_Write_Complex_FunctionalWithName_String_WithBaseId(fid, bid, groupname, num, name, paramname, value)
	_checkErrorCode(ier)


# from iriclib_geo.h
def iRIC_Geo_Polygon_Open(filename):
	ier, id = _iric.iRIC_Geo_Polygon_Open(filename)
	_checkErrorCode(ier)
	return id

def iRIC_Geo_Polygon_Read_IntegerValue(id):
	ier, value = _iric.iRIC_Geo_Polygon_Read_IntegerValue(id)
	_checkErrorCode(ier)
	return value

def iRIC_Geo_Polygon_Read_RealValue(id):
	ier, value = _iric.iRIC_Geo_Polygon_Read_RealValue(id)
	_checkErrorCode(ier)
	return value

def iRIC_Geo_Polygon_Read_PointCount(id):
	ier, size = _iric.iRIC_Geo_Polygon_Read_PointCount(id)
	_checkErrorCode(ier)
	return size

def iRIC_Geo_Polygon_Read_HoleCount(id):
	ier, count = _iric.iRIC_Geo_Polygon_Read_HoleCount(id)
	_checkErrorCode(ier)
	return count

def iRIC_Geo_Polygon_Read_HolePointCount(id, holeid):
	ier, count = _iric.iRIC_Geo_Polygon_Read_HolePointCount(id, holeid)
	_checkErrorCode(ier)
	return count

def iRIC_Geo_Polygon_Close(id):
	ier = _iric.iRIC_Geo_Polygon_Close(id)
	_checkErrorCode(ier)

def iRIC_Geo_RiverSurvey_Open(filename):
	ier, id = _iric.iRIC_Geo_RiverSurvey_Open(filename)
	_checkErrorCode(ier)
	return id

def iRIC_Geo_RiverSurvey_Read_Count(id):
	ier, count = _iric.iRIC_Geo_RiverSurvey_Read_Count(id)
	_checkErrorCode(ier)
	return count

def iRIC_Geo_RiverSurvey_Read_Position(id, pointid):
	ier, x, y = _iric.iRIC_Geo_RiverSurvey_Read_Position(id, pointid)
	_checkErrorCode(ier)
	return x, y

def iRIC_Geo_RiverSurvey_Read_Direction(id, pointid):
	ier, vx, vy = _iric.iRIC_Geo_RiverSurvey_Read_Direction(id, pointid)
	_checkErrorCode(ier)
	return vx, vy

def iRIC_Geo_RiverSurvey_Read_Name(id, pointid):
	ier, strvalue = _iric.iRIC_Geo_RiverSurvey_Read_Name(id, pointid)
	_checkErrorCode(ier)
	return strvalue

def iRIC_Geo_RiverSurvey_Read_RealName(id, pointid):
	ier, name = _iric.iRIC_Geo_RiverSurvey_Read_RealName(id, pointid)
	_checkErrorCode(ier)
	return name

def iRIC_Geo_RiverSurvey_Read_LeftShift(id, pointid):
	ier, shift = _iric.iRIC_Geo_RiverSurvey_Read_LeftShift(id, pointid)
	_checkErrorCode(ier)
	return shift

def iRIC_Geo_RiverSurvey_Read_AltitudeCount(id, pointid):
	ier, count = _iric.iRIC_Geo_RiverSurvey_Read_AltitudeCount(id, pointid)
	_checkErrorCode(ier)
	return count

def iRIC_Geo_RiverSurvey_Read_FixedPointL(id, pointid):
	ier, set, directionX, directionY, index = _iric.iRIC_Geo_RiverSurvey_Read_FixedPointL(id, pointid)
	_checkErrorCode(ier)
	return set, directionX, directionY, index

def iRIC_Geo_RiverSurvey_Read_FixedPointR(id, pointid):
	ier, set, directionX, directionY, index = _iric.iRIC_Geo_RiverSurvey_Read_FixedPointR(id, pointid)
	_checkErrorCode(ier)
	return set, directionX, directionY, index

def iRIC_Geo_RiverSurvey_Read_WaterSurfaceElevation(id, pointid):
	ier, set, value = _iric.iRIC_Geo_RiverSurvey_Read_WaterSurfaceElevation(id, pointid)
	_checkErrorCode(ier)
	return set, value

def iRIC_Geo_RiverSurvey_Close(id):
	ier = _iric.iRIC_Geo_RiverSurvey_Close(id)
	_checkErrorCode(ier)


# from iriclib_geoutil.h
def cg_iRIC_Read_Geo_Count(fid, name):
	ier, count = _iric.cg_iRIC_Read_Geo_Count(fid, name)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Geo_Filename(fid, name, geoid):
	ier, strvalue, type = _iric.cg_iRIC_Read_Geo_Filename(fid, name, geoid)
	_checkErrorCode(ier)
	return strvalue, type


# from iriclib_grid.h
def cg_iRIC_Read_Grid2d_Str_Size_WithGridId(fid, gid):
	ier, isize, jsize = _iric.cg_iRIC_Read_Grid2d_Str_Size_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return isize, jsize

def cg_iRIC_Read_Grid3d_Str_Size_WithGridId(fid, gid):
	ier, isize, jsize, ksize = _iric.cg_iRIC_Read_Grid3d_Str_Size_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return isize, jsize, ksize

def cg_iRIC_Read_Grid_TriangleElementsSize_WithGridId(fid, gid):
	ier, size = _iric.cg_iRIC_Read_Grid_TriangleElementsSize_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_Grid_TriangleElementsSize2_WithGridId(fid, gid):
	ier, size = _iric.cg_iRIC_Read_Grid_TriangleElementsSize2_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid):
	ier, count = _iric.cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid):
	ier, count = _iric.cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_IFaceCount_WithGridId(fid, gid):
	ier, count = _iric.cg_iRIC_Read_Grid_IFaceCount_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_JFaceCount_WithGridId(fid, gid):
	ier, count = _iric.cg_iRIC_Read_Grid_JFaceCount_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_KFaceCount_WithGridId(fid, gid):
	ier, count = _iric.cg_iRIC_Read_Grid_KFaceCount_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_FunctionalDimensionSize_WithGridId(fid, gid, name, dimname):
	ier, count = _iric.cg_iRIC_Read_Grid_FunctionalDimensionSize_WithGridId(fid, gid, name, dimname)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_FunctionalTimeSize_WithGridId(fid, gid, name):
	ier, count = _iric.cg_iRIC_Read_Grid_FunctionalTimeSize_WithGridId(fid, gid, name)
	_checkErrorCode(ier)
	return count


# from iriclib_grid_solverlib.h
def cg_iRIC_Read_Grid2d_Open_WithGridId(fid, gid):
	ier, grid_handle = _iric.cg_iRIC_Read_Grid2d_Open_WithGridId(fid, gid)
	_checkErrorCode(ier)
	return grid_handle

def cg_iRIC_Read_Sol_Grid2d_Open_WithGridId(fid, gid, solid):
	ier, grid_handle = _iric.cg_iRIC_Read_Sol_Grid2d_Open_WithGridId(fid, gid, solid)
	_checkErrorCode(ier)
	return grid_handle

def cg_iRIC_Read_Grid2d_Close(grid_handle):
	ier = _iric.cg_iRIC_Read_Grid2d_Close(grid_handle)
	_checkErrorCode(ier)

def cg_iRIC_Read_Grid2d_CellArea(grid_handle, cellId):
	ier, area = _iric.cg_iRIC_Read_Grid2d_CellArea(grid_handle, cellId)
	_checkErrorCode(ier)
	return area

def cg_iRIC_Read_Grid2d_FindCell(grid_handle, x, y):
	ier, cellId = _iric.cg_iRIC_Read_Grid2d_FindCell(grid_handle, x, y)
	_checkErrorCode(ier)
	return cellId

def cg_iRIC_Read_Grid2d_CellNodeCount(grid_handle, cellId):
	ier, count = _iric.cg_iRIC_Read_Grid2d_CellNodeCount(grid_handle, cellId)
	_checkErrorCode(ier)
	return count


# from iriclib_gui_coorp.h
def iRIC_Check_Cancel():
	ier = _iric.iRIC_Check_Cancel()
	return ier


# from iriclib_init.h
def cg_iRIC_Open(filename, mode):
	ier, fid = _iric.cg_iRIC_Open(filename, mode)
	_checkErrorCode(ier)
	return fid

def cg_iRIC_Close(fid):
	ier = _iric.cg_iRIC_Close(fid)
	_checkErrorCode(ier)

def iRIC_InitOption(option):
	ier = _iric.iRIC_InitOption(option)
	_checkErrorCode(ier)

def cg_iRIC_Flush(fid):
	ier = _iric.cg_iRIC_Flush(fid)
	_checkErrorCode(ier)


# from iriclib_not_withbaseid.h
def cg_iRIC_Read_Complex_Count(fid, groupname):
	ier, num = _iric.cg_iRIC_Read_Complex_Count(fid, groupname)
	_checkErrorCode(ier)
	return num

def cg_iRIC_Read_Complex_Integer(fid, groupname, num, name):
	ier, value = _iric.cg_iRIC_Read_Complex_Integer(fid, groupname, num, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_Complex_Real(fid, groupname, num, name):
	ier, value = _iric.cg_iRIC_Read_Complex_Real(fid, groupname, num, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_Complex_String(fid, groupname, num, name):
	ier, strvalue = _iric.cg_iRIC_Read_Complex_String(fid, groupname, num, name)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Read_Complex_FunctionalSize(fid, groupname, num, name):
	ier, size = _iric.cg_iRIC_Read_Complex_FunctionalSize(fid, groupname, num, name)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_Complex_FunctionalWithName_String(fid, groupname, num, name, paramname):
	ier, strvalue = _iric.cg_iRIC_Read_Complex_FunctionalWithName_String(fid, groupname, num, name, paramname)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Clear_Complex(fid):
	ier = _iric.cg_iRIC_Clear_Complex(fid)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_Integer(fid, groupname, num, name, value):
	ier = _iric.cg_iRIC_Write_Complex_Integer(fid, groupname, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_Real(fid, groupname, num, name, value):
	ier = _iric.cg_iRIC_Write_Complex_Real(fid, groupname, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_String(fid, groupname, num, name, value):
	ier = _iric.cg_iRIC_Write_Complex_String(fid, groupname, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_FunctionalWithName_String(fid, groupname, num, name, paramname, value):
	ier = _iric.cg_iRIC_Write_Complex_FunctionalWithName_String(fid, groupname, num, name, paramname, value)
	_checkErrorCode(ier)


# from iriclib_not_withgridid.h
def cg_iRIC_Read_BC_Count(fid, type):
	num = _iric.cg_iRIC_Read_BC_Count(fid, type)
	return num

def cg_iRIC_Read_BC_IndicesSize(fid, type, num):
	ier, size = _iric.cg_iRIC_Read_BC_IndicesSize(fid, type, num)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_BC_IndicesSize2(fid, type, num):
	ier, size = _iric.cg_iRIC_Read_BC_IndicesSize2(fid, type, num)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_BC_Integer(fid, type, num, name):
	ier, value = _iric.cg_iRIC_Read_BC_Integer(fid, type, num, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_BC_Real(fid, type, num, name):
	ier, value = _iric.cg_iRIC_Read_BC_Real(fid, type, num, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_BC_String(fid, type, num, name):
	ier, strvalue = _iric.cg_iRIC_Read_BC_String(fid, type, num, name)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Read_BC_FunctionalSize(fid, type, num, name):
	ier, size = _iric.cg_iRIC_Read_BC_FunctionalSize(fid, type, num, name)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_BC_FunctionalWithName_String(fid, type, num, name, paramname):
	ier, strvalue = _iric.cg_iRIC_Read_BC_FunctionalWithName_String(fid, type, num, name, paramname)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Clear_BC(fid):
	ier = _iric.cg_iRIC_Clear_BC(fid)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_Integer(fid, type, num, name, value):
	ier = _iric.cg_iRIC_Write_BC_Integer(fid, type, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_Real(fid, type, num, name, value):
	ier = _iric.cg_iRIC_Write_BC_Real(fid, type, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_String(fid, type, num, name, value):
	ier = _iric.cg_iRIC_Write_BC_String(fid, type, num, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_FunctionalWithName_String(fid, type, num, name, paramname, value):
	ier = _iric.cg_iRIC_Write_BC_FunctionalWithName_String(fid, type, num, name, paramname, value)
	_checkErrorCode(ier)

def cg_iRIC_Read_Grid2d_Str_Size(fid):
	ier, isize, jsize = _iric.cg_iRIC_Read_Grid2d_Str_Size(fid)
	_checkErrorCode(ier)
	return isize, jsize

def cg_iRIC_Read_Grid3d_Str_Size(fid):
	ier, isize, jsize, ksize = _iric.cg_iRIC_Read_Grid3d_Str_Size(fid)
	_checkErrorCode(ier)
	return isize, jsize, ksize

def cg_iRIC_Read_Grid_TriangleElementsSize(fid):
	ier, size = _iric.cg_iRIC_Read_Grid_TriangleElementsSize(fid)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_Grid_TriangleElementsSize2(fid):
	ier, size = _iric.cg_iRIC_Read_Grid_TriangleElementsSize2(fid)
	_checkErrorCode(ier)
	return size

def cg_iRIC_Read_Grid_NodeCount(fid):
	ier, count = _iric.cg_iRIC_Read_Grid_NodeCount(fid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_CellCount(fid):
	ier, count = _iric.cg_iRIC_Read_Grid_CellCount(fid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_IFaceCount(fid):
	ier, count = _iric.cg_iRIC_Read_Grid_IFaceCount(fid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_JFaceCount(fid):
	ier, count = _iric.cg_iRIC_Read_Grid_JFaceCount(fid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_KFaceCount(fid):
	ier, count = _iric.cg_iRIC_Read_Grid_KFaceCount(fid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_FunctionalDimensionSize(fid, name, dimname):
	ier, count = _iric.cg_iRIC_Read_Grid_FunctionalDimensionSize(fid, name, dimname)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid_FunctionalTimeSize(fid, name):
	ier, count = _iric.cg_iRIC_Read_Grid_FunctionalTimeSize(fid, name)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Grid2d_Open(fid):
	ier, grid_handle = _iric.cg_iRIC_Read_Grid2d_Open(fid)
	_checkErrorCode(ier)
	return grid_handle

def cg_iRIC_Read_Sol_Grid2d_Open(fid, solid):
	ier, grid_handle = _iric.cg_iRIC_Read_Sol_Grid2d_Open(fid, solid)
	_checkErrorCode(ier)
	return grid_handle

def cg_iRIC_Read_Sol_Particle_Count(fid, step):
	ier, count = _iric.cg_iRIC_Read_Sol_Particle_Count(fid, step)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Sol_ParticleGroup_Count(fid, step, groupname):
	ier, count = _iric.cg_iRIC_Read_Sol_ParticleGroup_Count(fid, step, groupname)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Write_Sol_ParticleGroup_GroupBegin(fid, name):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_GroupBegin(fid, name)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_GroupEnd(fid):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_GroupEnd(fid)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_Pos2d(fid, x, y):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_Pos2d(fid, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_Pos3d(fid, x, y, z):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_Pos3d(fid, x, y, z)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_Integer(fid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_Integer(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_Real(fid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_Real(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_PolyData_DataCount(fid, step, groupname):
	ier, count = _iric.cg_iRIC_Read_Sol_PolyData_DataCount(fid, step, groupname)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Sol_PolyData_CoordinateCount(fid, step, groupname):
	ier, count = _iric.cg_iRIC_Read_Sol_PolyData_CoordinateCount(fid, step, groupname)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Write_Sol_PolyData_GroupBegin(fid, name):
	ier = _iric.cg_iRIC_Write_Sol_PolyData_GroupBegin(fid, name)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_PolyData_GroupEnd(fid):
	ier = _iric.cg_iRIC_Write_Sol_PolyData_GroupEnd(fid)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_PolyData_Integer(fid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_PolyData_Integer(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_PolyData_Real(fid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_PolyData_Real(fid, name, value)
	_checkErrorCode(ier)


# from iriclib_sol_particle.h
def cg_iRIC_Read_Sol_Particle_Count_WithGridId(fid, gid, step):
	ier, count = _iric.cg_iRIC_Read_Sol_Particle_Count_WithGridId(fid, gid, step)
	_checkErrorCode(ier)
	return count


# from iriclib_sol_particlegroup.h
def cg_iRIC_Read_Sol_ParticleGroup_Count_WithGridId(fid, gid, step, groupname):
	ier, count = _iric.cg_iRIC_Read_Sol_ParticleGroup_Count_WithGridId(fid, gid, step, groupname)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Write_Sol_ParticleGroup_GroupBegin_WithGridId(fid, gid, name):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_GroupBegin_WithGridId(fid, gid, name)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_GroupEnd_WithGridId(fid, gid):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_GroupEnd_WithGridId(fid, gid)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_Pos2d_WithGridId(fid, gid, x, y):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_Pos2d_WithGridId(fid, gid, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_Pos3d_WithGridId(fid, gid, x, y, z):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_Pos3d_WithGridId(fid, gid, x, y, z)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_Integer_WithGridId(fid, gid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_Integer_WithGridId(fid, gid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_ParticleGroup_Real_WithGridId(fid, gid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_ParticleGroup_Real_WithGridId(fid, gid, name, value)
	_checkErrorCode(ier)


# from iriclib_sol_polydata.h
def cg_iRIC_Read_Sol_PolyData_DataCount_WithGridId(fid, gid, step, groupname):
	ier, count = _iric.cg_iRIC_Read_Sol_PolyData_DataCount_WithGridId(fid, gid, step, groupname)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Sol_PolyData_CoordinateCount_WithGridId(fid, gid, step, groupname):
	ier, count = _iric.cg_iRIC_Read_Sol_PolyData_CoordinateCount_WithGridId(fid, gid, step, groupname)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Write_Sol_PolyData_GroupBegin_WithGridId(fid, gid, name):
	ier = _iric.cg_iRIC_Write_Sol_PolyData_GroupBegin_WithGridId(fid, gid, name)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_PolyData_GroupEnd_WithGridId(fid, gid):
	ier = _iric.cg_iRIC_Write_Sol_PolyData_GroupEnd_WithGridId(fid, gid)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_PolyData_Integer_WithGridId(fid, gid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_PolyData_Integer_WithGridId(fid, gid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_PolyData_Real_WithGridId(fid, gid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_PolyData_Real_WithGridId(fid, gid, name, value)
	_checkErrorCode(ier)


# from iriclib_solution.h
def cg_iRIC_Read_Sol_Count(fid):
	ier, count = _iric.cg_iRIC_Read_Sol_Count(fid)
	_checkErrorCode(ier)
	return count

def cg_iRIC_Read_Sol_Time(fid, step):
	ier, time = _iric.cg_iRIC_Read_Sol_Time(fid, step)
	_checkErrorCode(ier)
	return time

def cg_iRIC_Read_Sol_Iteration(fid, step):
	ier, index = _iric.cg_iRIC_Read_Sol_Iteration(fid, step)
	_checkErrorCode(ier)
	return index

def cg_iRIC_Read_Sol_BaseIterative_Integer(fid, step, name):
	ier, value = _iric.cg_iRIC_Read_Sol_BaseIterative_Integer(fid, step, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_Sol_BaseIterative_Real(fid, step, name):
	ier, value = _iric.cg_iRIC_Read_Sol_BaseIterative_Real(fid, step, name)
	_checkErrorCode(ier)
	return value

def cg_iRIC_Read_Sol_BaseIterative_String(fid, step, name):
	ier, strvalue = _iric.cg_iRIC_Read_Sol_BaseIterative_String(fid, step, name)
	_checkErrorCode(ier)
	return strvalue

def cg_iRIC_Write_Sol_Time(fid, time):
	ier = _iric.cg_iRIC_Write_Sol_Time(fid, time)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Iteration(fid, index):
	ier = _iric.cg_iRIC_Write_Sol_Iteration(fid, index)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_BaseIterative_Integer(fid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_BaseIterative_Integer(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_BaseIterative_Real(fid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_BaseIterative_Real(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_BaseIterative_String(fid, name, value):
	ier = _iric.cg_iRIC_Write_Sol_BaseIterative_String(fid, name, value)
	_checkErrorCode(ier)

def cg_iRIC_Write_ErrorCode(fid, errorcode):
	ier = _iric.cg_iRIC_Write_ErrorCode(fid, errorcode)
	_checkErrorCode(ier)


# from iriclib_wrapper.h
def cg_iRIC_Read_BC_Indices_WithGridId(fid, gid, type, num):
	size = cg_iRIC_Read_BC_IndicesSize2_WithGridId(fid, gid, type, num)
	idx = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_BC_Indices_WithGridId(fid, gid, type, num, idx)
	_checkErrorCode(ier)
	return idx.get()

def cg_iRIC_Read_BC_Functional_WithGridId(fid, gid, type, num, name):
	size = cg_iRIC_Read_BC_FunctionalSize_WithGridId(fid, gid, type, num, name)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_BC_Functional_WithGridId(fid, gid, type, num, name, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_BC_FunctionalWithName_WithGridId(fid, gid, type, num, name, paramname):
	size = cg_iRIC_Read_BC_FunctionalSize_WithGridId(fid, gid, type, num, name)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_BC_FunctionalWithName_WithGridId(fid, gid, type, num, name, paramname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_BC_Indices_WithGridId(fid, gid, type, num, idx_arr):
	idx = IntArrayContainer(idx_arr.size)
	idx.set(idx_arr)
	ier = _iric.cg_iRIC_Write_BC_Indices_WithGridId(fid, gid, type, num, idx)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_Indices2_WithGridId(fid, gid, type, num, idx_arr):
	idx = IntArrayContainer(idx_arr.size)
	idx.set(idx_arr)
	ier = _iric.cg_iRIC_Write_BC_Indices2_WithGridId(fid, gid, type, num, idx)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_Functional_WithGridId(fid, gid, type, num, name, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_BC_Functional_WithGridId(fid, gid, type, num, name, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_FunctionalWithName_WithGridId(fid, gid, type, num, name, paramname, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_BC_FunctionalWithName_WithGridId(fid, gid, type, num, name, paramname, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Functional(fid, name):
	size = cg_iRIC_Read_FunctionalSize(fid, name)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Functional(fid, name, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_FunctionalWithName(fid, name, paramname):
	size = cg_iRIC_Read_FunctionalSize(fid, name)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_FunctionalWithName(fid, name, paramname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Functional(fid, name, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Functional(fid, name, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_FunctionalWithName(fid, name, paramname, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_FunctionalWithName(fid, name, paramname, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Complex_Functional_WithBaseId(fid, bid, groupname, num, name):
	size = cg_iRIC_Read_Complex_FunctionalSize_WithBaseId(fid, bid, groupname, num, name)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Complex_Functional_WithBaseId(fid, bid, groupname, num, name, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Complex_FunctionalWithName_WithBaseId(fid, bid, groupname, num, name, paramname):
	size = cg_iRIC_Read_Complex_FunctionalSize_WithBaseId(fid, bid, groupname, num, name)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Complex_FunctionalWithName_WithBaseId(fid, bid, groupname, num, name, paramname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Complex_Node_WithGridId(fid, gid, groupname):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Complex_Node_WithGridId(fid, gid, groupname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Complex_Cell_WithGridId(fid, gid, groupname):
	size = cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Complex_Cell_WithGridId(fid, gid, groupname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Complex_Functional_WithBaseId(fid, bid, groupname, num, name, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Complex_Functional_WithBaseId(fid, bid, groupname, num, name, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_FunctionalWithName_WithBaseId(fid, bid, groupname, num, name, paramname, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Complex_FunctionalWithName_WithBaseId(fid, bid, groupname, num, name, paramname, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Complex_Node_WithGridId(fid, gid, groupname, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Complex_Node_WithGridId(fid, gid, groupname, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Complex_Cell_WithGridId(fid, gid, groupname, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Complex_Cell_WithGridId(fid, gid, groupname, v)
	_checkErrorCode(ier)

def iRIC_Geo_Polygon_Read_Points(id):
	size = iRIC_Geo_Polygon_Read_PointCount(id)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.iRIC_Geo_Polygon_Read_Points(id, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def iRIC_Geo_Polygon_Read_HolePoints(id, holeid):
	size = iRIC_Geo_Polygon_Read_HolePointCount(id, holeid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.iRIC_Geo_Polygon_Read_HolePoints(id, holeid, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def iRIC_Geo_RiverSurvey_Read_Altitudes(id, pointid):
	size = iRIC_Geo_RiverSurvey_Read_AltitudeCount(id, pointid)
	position = RealArrayContainer(size)
	height = RealArrayContainer(size)
	active = IntArrayContainer(size)
	ier = _iric.iRIC_Geo_RiverSurvey_Read_Altitudes(id, pointid, position, height, active)
	_checkErrorCode(ier)
	return position.get(), height.get(), active.get()

def cg_iRIC_Read_Grid2d_Coords_WithGridId(fid, gid):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid2d_Coords_WithGridId(fid, gid, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Grid3d_Coords_WithGridId(fid, gid):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	z = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid3d_Coords_WithGridId(fid, gid, x, y, z)
	_checkErrorCode(ier)
	return x.get(), y.get(), z.get()

def cg_iRIC_Read_Grid_TriangleElements_WithGridId(fid, gid):
	size = cg_iRIC_Read_Grid_TriangleElementsSize2_WithGridId(fid, gid)
	id = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_TriangleElements_WithGridId(fid, gid, id)
	_checkErrorCode(ier)
	return id.get()

def cg_iRIC_Read_Grid_Real_Node_WithGridId(fid, gid, name):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Real_Node_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Integer_Node_WithGridId(fid, gid, name):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Integer_Node_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Real_Cell_WithGridId(fid, gid, name):
	size = cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Real_Cell_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Integer_Cell_WithGridId(fid, gid, name):
	size = cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Integer_Cell_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_FunctionalDimension_Integer_WithGridId(fid, gid, name, dimname):
	size = cg_iRIC_Read_Grid_FunctionalDimensionSize_WithGridId(fid, gid, name, dimname)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_FunctionalDimension_Integer_WithGridId(fid, gid, name, dimname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_FunctionalDimension_Real_WithGridId(fid, gid, name, dimname):
	size = cg_iRIC_Read_Grid_FunctionalDimensionSize_WithGridId(fid, gid, name, dimname)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_FunctionalDimension_Real_WithGridId(fid, gid, name, dimname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_FunctionalTime_WithGridId(fid, gid, name):
	size = cg_iRIC_Read_Grid_FunctionalTimeSize_WithGridId(fid, gid, name)
	time = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_FunctionalTime_WithGridId(fid, gid, name, time)
	_checkErrorCode(ier)
	return time.get()

def cg_iRIC_Read_Grid_Functional_Integer_Node_WithGridId(fid, gid, name, dimid):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Functional_Integer_Node_WithGridId(fid, gid, name, dimid, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Functional_Real_Node_WithGridId(fid, gid, name, dimid):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Functional_Real_Node_WithGridId(fid, gid, name, dimid, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Functional_Integer_Cell_WithGridId(fid, gid, name, dimid):
	size = cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Functional_Integer_Cell_WithGridId(fid, gid, name, dimid, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Functional_Real_Cell_WithGridId(fid, gid, name, dimid):
	size = cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Functional_Real_Cell_WithGridId(fid, gid, name, dimid, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Grid1d_Coords_WithGridId(fid, isize, x_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	ier, gid = _iric.cg_iRIC_Write_Grid1d_Coords_WithGridId(fid, isize, x)
	_checkErrorCode(ier)
	return gid

def cg_iRIC_Write_Grid2d_Coords_WithGridId(fid, isize, jsize, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier, gid = _iric.cg_iRIC_Write_Grid2d_Coords_WithGridId(fid, isize, jsize, x, y)
	_checkErrorCode(ier)
	return gid

def cg_iRIC_Write_Grid3d_Coords_WithGridId(fid, isize, jsize, ksize, x_arr, y_arr, z_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	z = RealArrayContainer(z_arr.size)
	z.set(z_arr)
	ier, gid = _iric.cg_iRIC_Write_Grid3d_Coords_WithGridId(fid, isize, jsize, ksize, x, y, z)
	_checkErrorCode(ier)
	return gid

def cg_iRIC_Write_Grid_Real_Node_WithGridId(fid, gid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Real_Node_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Integer_Node_WithGridId(fid, gid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Integer_Node_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Real_Cell_WithGridId(fid, gid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Real_Cell_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Integer_Cell_WithGridId(fid, gid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Integer_Cell_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Grid2d_InterpolateWithCell(grid_handle, x, y, cellId):
	size = cg_iRIC_Read_Grid2d_CellNodeCount(grid_handle, cellId)
	nodeids = IntArrayContainer(size)
	weights = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid2d_InterpolateWithCell(grid_handle, x, y, cellId, nodeids, weights)
	_checkErrorCode(ier)
	return nodeids.get(), weights.get()

def cg_iRIC_Read_Complex_Functional(fid, groupname, num, name):
	size = cg_iRIC_Read_Complex_FunctionalSize(fid, groupname, num, name)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Complex_Functional(fid, groupname, num, name, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Complex_FunctionalWithName(fid, groupname, num, name, paramname):
	size = cg_iRIC_Read_Complex_FunctionalSize(fid, groupname, num, name)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Complex_FunctionalWithName(fid, groupname, num, name, paramname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Complex_Functional(fid, groupname, num, name, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Complex_Functional(fid, groupname, num, name, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Complex_FunctionalWithName(fid, groupname, num, name, paramname, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Complex_FunctionalWithName(fid, groupname, num, name, paramname, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_BC_Indices(fid, type, num):
	size = cg_iRIC_Read_BC_IndicesSize2(fid, type, num)
	idx = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_BC_Indices(fid, type, num, idx)
	_checkErrorCode(ier)
	return idx.get()

def cg_iRIC_Read_BC_Functional(fid, type, num, name):
	size = cg_iRIC_Read_BC_FunctionalSize(fid, type, num, name)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_BC_Functional(fid, type, num, name, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_BC_FunctionalWithName(fid, type, num, name, paramname):
	size = cg_iRIC_Read_BC_FunctionalSize(fid, type, num, name)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_BC_FunctionalWithName(fid, type, num, name, paramname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_BC_Indices(fid, type, num, idx_arr):
	idx = IntArrayContainer(idx_arr.size)
	idx.set(idx_arr)
	ier = _iric.cg_iRIC_Write_BC_Indices(fid, type, num, idx)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_Indices2(fid, type, num, idx_arr):
	idx = IntArrayContainer(idx_arr.size)
	idx.set(idx_arr)
	ier = _iric.cg_iRIC_Write_BC_Indices2(fid, type, num, idx)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_Functional(fid, type, num, name, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_BC_Functional(fid, type, num, name, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_BC_FunctionalWithName(fid, type, num, name, paramname, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_BC_FunctionalWithName(fid, type, num, name, paramname, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Grid_Complex_Node(fid, groupname):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Complex_Node(fid, groupname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Complex_Cell(fid, groupname):
	size = cg_iRIC_Read_Grid_CellCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Complex_Cell(fid, groupname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Grid_Complex_Node(fid, groupname, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Complex_Node(fid, groupname, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Complex_Cell(fid, groupname, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Complex_Cell(fid, groupname, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Grid2d_Coords(fid):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid2d_Coords(fid, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Grid3d_Coords(fid):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	z = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid3d_Coords(fid, x, y, z)
	_checkErrorCode(ier)
	return x.get(), y.get(), z.get()

def cg_iRIC_Read_Grid_TriangleElements(fid):
	size = cg_iRIC_Read_Grid_TriangleElementsSize2(fid)
	id = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_TriangleElements(fid, id)
	_checkErrorCode(ier)
	return id.get()

def cg_iRIC_Read_Grid_Real_Node(fid, name):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Real_Node(fid, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Integer_Node(fid, name):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Integer_Node(fid, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Real_Cell(fid, name):
	size = cg_iRIC_Read_Grid_CellCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Real_Cell(fid, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Integer_Cell(fid, name):
	size = cg_iRIC_Read_Grid_CellCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Integer_Cell(fid, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_FunctionalDimension_Integer(fid, name, dimname):
	size = cg_iRIC_Read_Grid_FunctionalDimensionSize(fid, name, dimname)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_FunctionalDimension_Integer(fid, name, dimname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_FunctionalDimension_Real(fid, name, dimname):
	size = cg_iRIC_Read_Grid_FunctionalDimensionSize(fid, name, dimname)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_FunctionalDimension_Real(fid, name, dimname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_FunctionalTime(fid, name):
	size = cg_iRIC_Read_Grid_FunctionalTimeSize(fid, name)
	time = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_FunctionalTime(fid, name, time)
	_checkErrorCode(ier)
	return time.get()

def cg_iRIC_Read_Grid_Functional_Integer_Node(fid, name, dimid):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Functional_Integer_Node(fid, name, dimid, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Functional_Real_Node(fid, name, dimid):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Functional_Real_Node(fid, name, dimid, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Functional_Integer_Cell(fid, name, dimid):
	size = cg_iRIC_Read_Grid_CellCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Functional_Integer_Cell(fid, name, dimid, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Grid_Functional_Real_Cell(fid, name, dimid):
	size = cg_iRIC_Read_Grid_CellCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Grid_Functional_Real_Cell(fid, name, dimid, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Grid1d_Coords(fid, isize, x_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	ier = _iric.cg_iRIC_Write_Grid1d_Coords(fid, isize, x)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid2d_Coords(fid, isize, jsize, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Grid2d_Coords(fid, isize, jsize, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid3d_Coords(fid, isize, jsize, ksize, x_arr, y_arr, z_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	z = RealArrayContainer(z_arr.size)
	z.set(z_arr)
	ier = _iric.cg_iRIC_Write_Grid3d_Coords(fid, isize, jsize, ksize, x, y, z)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Real_Node(fid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Real_Node(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Integer_Node(fid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Integer_Node(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Real_Cell(fid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Real_Cell(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Grid_Integer_Cell(fid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Grid_Integer_Cell(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_Cell_Integer(fid, step, name):
	size = cg_iRIC_Read_Grid_CellCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Cell_Integer(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_Cell_Real(fid, step, name):
	size = cg_iRIC_Read_Grid_CellCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Cell_Real(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_Cell_Integer(fid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Cell_Integer(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Cell_Real(fid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Cell_Real(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_Grid2d_Coords(fid, step):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Grid2d_Coords(fid, step, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Sol_Grid3d_Coords(fid, step):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	z = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Grid3d_Coords(fid, step, x, y, z)
	_checkErrorCode(ier)
	return x.get(), y.get(), z.get()

def cg_iRIC_Write_Sol_Grid2d_Coords(fid, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Sol_Grid2d_Coords(fid, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Grid3d_Coords(fid, x_arr, y_arr, z_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	z = RealArrayContainer(z_arr.size)
	z.set(z_arr)
	ier = _iric.cg_iRIC_Write_Sol_Grid3d_Coords(fid, x, y, z)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_IFace_Integer(fid, step, name):
	size = cg_iRIC_Read_Grid_IFaceCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_IFace_Integer(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_IFace_Real(fid, step, name):
	size = cg_iRIC_Read_Grid_IFaceCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_IFace_Real(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_IFace_Integer(fid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_IFace_Integer(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_IFace_Real(fid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_IFace_Real(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_JFace_Integer(fid, step, name):
	size = cg_iRIC_Read_Grid_JFaceCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_JFace_Integer(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_JFace_Real(fid, step, name):
	size = cg_iRIC_Read_Grid_JFaceCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_JFace_Real(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_JFace_Integer(fid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_JFace_Integer(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_JFace_Real(fid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_JFace_Real(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_KFace_Integer(fid, step, name):
	size = cg_iRIC_Read_Grid_KFaceCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_KFace_Integer(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_KFace_Real(fid, step, name):
	size = cg_iRIC_Read_Grid_KFaceCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_KFace_Real(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_KFace_Integer(fid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_KFace_Integer(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_KFace_Real(fid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_KFace_Real(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_Node_Integer(fid, step, name):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Node_Integer(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_Node_Real(fid, step, name):
	size = cg_iRIC_Read_Grid_NodeCount(fid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Node_Real(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_Node_Integer(fid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Node_Integer(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Node_Real(fid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Node_Real(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_Particle_Pos2d(fid, step):
	size = cg_iRIC_Read_Sol_Particle_Count(fid, step)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Particle_Pos2d(fid, step, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Sol_Particle_Pos3d(fid, step):
	size = cg_iRIC_Read_Sol_Particle_Count(fid, step)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	z = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Particle_Pos3d(fid, step, x, y, z)
	_checkErrorCode(ier)
	return x.get(), y.get(), z.get()

def cg_iRIC_Read_Sol_Particle_Real(fid, step, name):
	size = cg_iRIC_Read_Sol_Particle_Count(fid, step)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Particle_Real(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_Particle_Integer(fid, step, name):
	size = cg_iRIC_Read_Sol_Particle_Count(fid, step)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Particle_Integer(fid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_Particle_Pos2d(fid, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Sol_Particle_Pos2d(fid, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Particle_Pos3d(fid, x_arr, y_arr, z_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	z = RealArrayContainer(z_arr.size)
	z.set(z_arr)
	ier = _iric.cg_iRIC_Write_Sol_Particle_Pos3d(fid, x, y, z)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Particle_Real(fid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Particle_Real(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Particle_Integer(fid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Particle_Integer(fid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_ParticleGroup_Pos2d(fid, step, groupname):
	size = cg_iRIC_Read_Sol_ParticleGroup_Count(fid, step, groupname)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_ParticleGroup_Pos2d(fid, step, groupname, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Sol_ParticleGroup_Pos3d(fid, step, groupname):
	size = cg_iRIC_Read_Sol_ParticleGroup_Count(fid, step, groupname)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	z = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_ParticleGroup_Pos3d(fid, step, groupname, x, y, z)
	_checkErrorCode(ier)
	return x.get(), y.get(), z.get()

def cg_iRIC_Read_Sol_ParticleGroup_Real(fid, step, groupname, name):
	size = cg_iRIC_Read_Sol_ParticleGroup_Count(fid, step, groupname)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_ParticleGroup_Real(fid, step, groupname, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_ParticleGroup_Integer(fid, step, groupname, name):
	size = cg_iRIC_Read_Sol_ParticleGroup_Count(fid, step, groupname)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_ParticleGroup_Integer(fid, step, groupname, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_PolyData_Pos2d(fid, step, groupname):
	size = cg_iRIC_Read_Sol_PolyData_CoordinateCount(fid, step, groupname)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_PolyData_Pos2d(fid, step, groupname, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Sol_PolyData_Type(fid, step, groupname):
	size = cg_iRIC_Read_Sol_PolyData_DataCount(fid, step, groupname)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_PolyData_Type(fid, step, groupname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_PolyData_Real(fid, step, groupname, name):
	size = cg_iRIC_Read_Sol_PolyData_DataCount(fid, step, groupname)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_PolyData_Real(fid, step, groupname, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_PolyData_Integer(fid, step, groupname, name):
	size = cg_iRIC_Read_Sol_PolyData_DataCount(fid, step, groupname)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_PolyData_Integer(fid, step, groupname, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_PolyData_Polygon(fid, numPoints, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Sol_PolyData_Polygon(fid, numPoints, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_PolyData_Polyline(fid, numPoints, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Sol_PolyData_Polyline(fid, numPoints, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_Cell_Integer_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Cell_Integer_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_Cell_Real_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_CellCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Cell_Real_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_Cell_Integer_WithGridId(fid, gid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Cell_Integer_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Cell_Real_WithGridId(fid, gid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Cell_Real_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_Grid2d_Coords_WithGridId(fid, gid, step):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Grid2d_Coords_WithGridId(fid, gid, step, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Sol_Grid3d_Coords_WithGridId(fid, gid, step):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	z = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Grid3d_Coords_WithGridId(fid, gid, step, x, y, z)
	_checkErrorCode(ier)
	return x.get(), y.get(), z.get()

def cg_iRIC_Write_Sol_Grid2d_Coords_WithGridId(fid, gid, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Sol_Grid2d_Coords_WithGridId(fid, gid, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Grid3d_Coords_WithGridId(fid, gid, x_arr, y_arr, z_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	z = RealArrayContainer(z_arr.size)
	z.set(z_arr)
	ier = _iric.cg_iRIC_Write_Sol_Grid3d_Coords_WithGridId(fid, gid, x, y, z)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_IFace_Integer_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_IFaceCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_IFace_Integer_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_IFace_Real_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_IFaceCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_IFace_Real_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_IFace_Integer_WithGridId(fid, gid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_IFace_Integer_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_IFace_Real_WithGridId(fid, gid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_IFace_Real_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_JFace_Integer_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_JFaceCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_JFace_Integer_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_JFace_Real_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_JFaceCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_JFace_Real_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_JFace_Integer_WithGridId(fid, gid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_JFace_Integer_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_JFace_Real_WithGridId(fid, gid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_JFace_Real_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_KFace_Integer_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_KFaceCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_KFace_Integer_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_KFace_Real_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_KFaceCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_KFace_Real_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_KFace_Integer_WithGridId(fid, gid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_KFace_Integer_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_KFace_Real_WithGridId(fid, gid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_KFace_Real_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_Node_Integer_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Node_Integer_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_Node_Real_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Grid_NodeCount_WithGridId(fid, gid)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Node_Real_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_Node_Integer_WithGridId(fid, gid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Node_Integer_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Node_Real_WithGridId(fid, gid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Node_Real_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_Particle_Pos2d_WithGridId(fid, gid, step):
	size = cg_iRIC_Read_Sol_Particle_Count_WithGridId(fid, gid, step)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Particle_Pos2d_WithGridId(fid, gid, step, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Sol_Particle_Pos3d_WithGridId(fid, gid, step):
	size = cg_iRIC_Read_Sol_Particle_Count_WithGridId(fid, gid, step)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	z = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Particle_Pos3d_WithGridId(fid, gid, step, x, y, z)
	_checkErrorCode(ier)
	return x.get(), y.get(), z.get()

def cg_iRIC_Read_Sol_Particle_Real_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Sol_Particle_Count_WithGridId(fid, gid, step)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Particle_Real_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_Particle_Integer_WithGridId(fid, gid, step, name):
	size = cg_iRIC_Read_Sol_Particle_Count_WithGridId(fid, gid, step)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_Particle_Integer_WithGridId(fid, gid, step, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_Particle_Pos2d_WithGridId(fid, gid, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Sol_Particle_Pos2d_WithGridId(fid, gid, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Particle_Pos3d_WithGridId(fid, gid, x_arr, y_arr, z_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	z = RealArrayContainer(z_arr.size)
	z.set(z_arr)
	ier = _iric.cg_iRIC_Write_Sol_Particle_Pos3d_WithGridId(fid, gid, x, y, z)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Particle_Real_WithGridId(fid, gid, name, v_arr):
	v = RealArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Particle_Real_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_Particle_Integer_WithGridId(fid, gid, name, v_arr):
	v = IntArrayContainer(v_arr.size)
	v.set(v_arr)
	ier = _iric.cg_iRIC_Write_Sol_Particle_Integer_WithGridId(fid, gid, name, v)
	_checkErrorCode(ier)

def cg_iRIC_Read_Sol_ParticleGroup_Pos2d_WithGridId(fid, gid, step, groupname):
	size = cg_iRIC_Read_Sol_ParticleGroup_Count_WithGridId(fid, gid, step, groupname)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_ParticleGroup_Pos2d_WithGridId(fid, gid, step, groupname, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Sol_ParticleGroup_Pos3d_WithGridId(fid, gid, step, groupname):
	size = cg_iRIC_Read_Sol_ParticleGroup_Count_WithGridId(fid, gid, step, groupname)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	z = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_ParticleGroup_Pos3d_WithGridId(fid, gid, step, groupname, x, y, z)
	_checkErrorCode(ier)
	return x.get(), y.get(), z.get()

def cg_iRIC_Read_Sol_ParticleGroup_Real_WithGridId(fid, gid, step, groupname, name):
	size = cg_iRIC_Read_Sol_ParticleGroup_Count_WithGridId(fid, gid, step, groupname)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_ParticleGroup_Real_WithGridId(fid, gid, step, groupname, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_ParticleGroup_Integer_WithGridId(fid, gid, step, groupname, name):
	size = cg_iRIC_Read_Sol_ParticleGroup_Count_WithGridId(fid, gid, step, groupname)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_ParticleGroup_Integer_WithGridId(fid, gid, step, groupname, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_PolyData_Pos2d_WithGridId(fid, gid, step, groupname):
	size = cg_iRIC_Read_Sol_PolyData_CoordinateCount_WithGridId(fid, gid, step, groupname)
	x = RealArrayContainer(size)
	y = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_PolyData_Pos2d_WithGridId(fid, gid, step, groupname, x, y)
	_checkErrorCode(ier)
	return x.get(), y.get()

def cg_iRIC_Read_Sol_PolyData_Type_WithGridId(fid, gid, step, groupname):
	size = cg_iRIC_Read_Sol_PolyData_DataCount_WithGridId(fid, gid, step, groupname)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_PolyData_Type_WithGridId(fid, gid, step, groupname, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_PolyData_Real_WithGridId(fid, gid, step, groupname, name):
	size = cg_iRIC_Read_Sol_PolyData_DataCount_WithGridId(fid, gid, step, groupname)
	v = RealArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_PolyData_Real_WithGridId(fid, gid, step, groupname, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Read_Sol_PolyData_Integer_WithGridId(fid, gid, step, groupname, name):
	size = cg_iRIC_Read_Sol_PolyData_DataCount_WithGridId(fid, gid, step, groupname)
	v = IntArrayContainer(size)
	ier = _iric.cg_iRIC_Read_Sol_PolyData_Integer_WithGridId(fid, gid, step, groupname, name, v)
	_checkErrorCode(ier)
	return v.get()

def cg_iRIC_Write_Sol_PolyData_Polygon_WithGridId(fid, gid, numPoints, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Sol_PolyData_Polygon_WithGridId(fid, gid, numPoints, x, y)
	_checkErrorCode(ier)

def cg_iRIC_Write_Sol_PolyData_Polyline_WithGridId(fid, gid, numPoints, x_arr, y_arr):
	x = RealArrayContainer(x_arr.size)
	x.set(x_arr)
	y = RealArrayContainer(y_arr.size)
	y.set(y_arr)
	ier = _iric.cg_iRIC_Write_Sol_PolyData_Polyline_WithGridId(fid, gid, numPoints, x, y)
	_checkErrorCode(ier)


def cg_iRIC_Read_Grid2d_Interpolate(grid_handle, x, y):
    cellId = cg_iRIC_Read_Grid2d_FindCell(grid_handle, x, y)
    return cg_iRIC_Read_Grid2d_InterpolateWithCell(grid_handle, x, y, cellId)
