######################################################################
# Automatically generated by qmake (2.01a) ? 11 5 22:15:18 2014
######################################################################

TEMPLATE = app
TARGET = test14
CONFIG += debug_and_release

include( ../../../paths.pri )

QT -= core

LIBS += -liriclib

win32{
LIBS += -lcgnsdll
}
unix{
LIBS += -lcgns
}

# Input

SOURCES += test14.cpp
